export const ATTEMPT_CONNECTION = 'auth/ATTEMPT_CONNECTION'
export const DISCONNECT = 'auth/DISCONNECT'
export const SIGNIN = 'user/SIGNIN'
export const SIGNOUT = 'user/SIGNOUT'
export const ADD_PRODUCT = 'user/ADD_PRODUCT'
export const REMOVE_PRODUCT = 'user/REMOVE_PRODUCT'
export const SAVE_PORTFOLIO = 'user/SAVE_PORTFOLIO'
export const LOAD_PAGE = 'dom/LOAD_PAGE'

export const PRODUCTS = 'portfolio/PRODUCTS'
export const PRODUCTS_SELECTED = 'portfolio/PRODUCTS_SELECTED'
export const PRODUCTS_RESETED = 'portfolio/PRODUCTS_RESETED'
export const PRODUCTS_TAB_SELECTED = 'portfolio/PRODUCTS_TAB_SELECTED'